include:
  - project: $CATALOG_PATH
    file:
      - vault-ci.yml
      - kaniko-ci.yml
    ref: main

default:
  image: alpine:latest

cache:
  paths:
    - node_modules

variables:
  TAG: "${CI_COMMIT_REF_NAME}"
  DOCKERFILE: Dockerfile
  REGISTRY_URL: "${REGISTRY_HOST}/${PROJECT_PATH}"

stages:
  - read-secret
  - docker-build
  - sonar

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

sonar-app:
  variables:
  stage: sonar
  extends:
    - .sonar:sonar-scanner
 
docker-build:
  variables:
    WORKING_DIR: "."
    IMAGE_NAMES: node-prototype:${CI_COMMIT_REF_SLUG} node-kaamelott:latest node-prototype:0.0.1
    TAG: "${CI_COMMIT_REF_SLUG}"
  stage: docker-build
  extends:
    - .kaniko:build-push

